# SDP PROJECT PoC Demo
FROM ubuntu:20.04
RUN apt update && apt install -y python3 python3-pip net-tools openssh-client curl iputils-ping
RUN pip3 install pycrypto && pip3 install mysql-connector-python && pip3 install paho-mqtt

#COPY . /app
#RUN make /app
#CMD python /app/app.py
